chore: process crawler results before committing

diff --git a/.github/workflows/crawler.yml b/.github/workflows/crawler.yml
--- a/.github/workflows/crawler.yml
+++ b/.github/workflows/crawler.yml
@@ -65,23 +65,33 @@ jobs:
         run: |
           chmod +x rippled/rippled
           ./rippled/rippled &
-          cargo run --features crawler --bin crawler -- --seed-addrs 127.0.0.1:5005 --rpc-addr 127.0.0.1:54321 &
+          cargo run --features crawler --bin crawler -- --seed-addrs 127.0.0.1:51235 --rpc-addr 127.0.0.1:54321 &
           mkdir -p results/crawler
           rm -f results/crawler/latest.json
           # After 30 min, query rpc and send SIGINT.
           sleep 30m
-          curl --data-binary '{"jsonrpc": "2.0", "id":0, "method": "getmetrics", "params": [] }' -H 'content-type: application/json' http://127.0.0.1:54321/ > results/crawler/latest.json
+          curl --data-binary '{"jsonrpc": "2.0", "id":0, "method": "getmetrics", "params": { "file": "latest.json" } }' -H 'content-type: application/json' http://127.0.0.1:54321/
           kill -2 $(pidof crawler) $(pidof rippled)
-          cat results/crawler/latest.json
-      - name: Git
+      - name: Process results
         run: |
           FILENAME=$(date +%Y-%m-%d)
+          cat latest.json
+          # If the result contains any error, fail workflow
+          if grep "error" latest.json; then
+            echo "Aborting. Crawler results contained an error"
+            exit 1
+          fi
+          mkdir -p results/crawler
+          rm -f results/crawler/latest.json
+          mv latest.json results/crawler/latest.json
           cd results/crawler
           cp latest.json $FILENAME.json
           gzip $FILENAME.json
+      - name: Git
+        run: |
           git config user.name 'github-actions[bot]'
           git config user.email 'github-actions[bot]@users.noreply.github.com'
           git pull
-          git add ./
+          git add results/crawler
           git commit -m "ci: crawler results"
           git push
